// Generated by CoffeeScript 1.6.3
(function() {
  var _this = this;

  require.config({
    paths: {
      "jquery": "vendor/jquery/jquery",
      "lodash": "vendor/lodash/dist/lodash",
      "howler": "vendor/howler/howler"
    }
  });

  requirejs(['jquery', 'howler', 'lodash'], function($, howler, _) {
    return console.log("loaded up");
  });

  console.log('\'Allo \'Allo!');

}).call(this);
